package com.darach.openlibrarybooks.core.designsystem.theme

import androidx.compose.ui.graphics.Color

/**
 * Material 3 Expressive colour palette for light mode.
 */
val primaryLight = Color(0xFF006B2E)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF00873C)
val onPrimaryContainerLight = Color(0xFFF7FFF3)
val secondaryLight = Color(0xFF3E6844)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFBCEBBF)
val onSecondaryContainerLight = Color(0xFF426C48)
val tertiaryLight = Color(0xFF006B2E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF00873C)
val onTertiaryContainerLight = Color(0xFFF7FFF3)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF5FBF1)
val onBackgroundLight = Color(0xFF171D17)
val surfaceLight = Color(0xFFF5FBF1)
val onSurfaceLight = Color(0xFF171D17)
val surfaceVariantLight = Color(0xFFD9E6D6)
val onSurfaceVariantLight = Color(0xFF3E4A3E)
val outlineLight = Color(0xFF6E7A6D)
val outlineVariantLight = Color(0xFFBDCABA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C322B)
val inverseOnSurfaceLight = Color(0xFFECF3E8)
val inversePrimaryLight = Color(0xFF69DE83)
val surfaceDimLight = Color(0xFFD5DCD2)
val surfaceBrightLight = Color(0xFFF5FBF1)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF6EB)
val surfaceContainerLight = Color(0xFFE9F0E5)
val surfaceContainerHighLight = Color(0xFFE3EAE0)
val surfaceContainerHighestLight = Color(0xFFDEE4DA)

/**
 * Material 3 Expressive colour palette for dark mode.
 * Provides proper contrast and accessibility in low-light conditions.
 */
val primaryDark = Color(0xFF69DE83)
val onPrimaryDark = Color(0xFF003915)
val primaryContainerDark = Color(0xFF2BA552)
val onPrimaryContainerDark = Color(0xFF00220A)
val secondaryDark = Color(0xFFA4D2A7)
val onSecondaryDark = Color(0xFF0E3819)
val secondaryContainerDark = Color(0xFF295230)
val onSecondaryContainerDark = Color(0xFF96C499)
val tertiaryDark = Color(0xFF69DE83)
val onTertiaryDark = Color(0xFF003915)
val tertiaryContainerDark = Color(0xFF2BA552)
val onTertiaryContainerDark = Color(0xFF00220A)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F150F)
val onBackgroundDark = Color(0xFFDEE4DA)
val surfaceDark = Color(0xFF0F150F)
val onSurfaceDark = Color(0xFFDEE4DA)
val surfaceVariantDark = Color(0xFF3E4A3E)
val onSurfaceVariantDark = Color(0xFFBDCABA)
val outlineDark = Color(0xFF879486)
val outlineVariantDark = Color(0xFF3E4A3E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE4DA)
val inverseOnSurfaceDark = Color(0xFF2C322B)
val inversePrimaryDark = Color(0xFF006D2F)
val surfaceDimDark = Color(0xFF0F150F)
val surfaceBrightDark = Color(0xFF343B34)
val surfaceContainerLowestDark = Color(0xFF0A100A)
val surfaceContainerLowDark = Color(0xFF171D17)
val surfaceContainerDark = Color(0xFF1B211B)
val surfaceContainerHighDark = Color(0xFF252C25)
val surfaceContainerHighestDark = Color(0xFF30362F)

/**
 * Additional colours for special use cases.
 */
val darkGreen = Color(0xFF005B2C)
val midGreen = Color(0xFF198F52)
val lightGreenAccent = Color(0xFF4DBA84)
val goldOchre = Color(0xFFD9A762)
